export default function PredictionResults({ result }) {
  const { stage1, stage2, stage3, stage4, final_recommendation } = result;

  const formatProb = (p) => (p !== null && p !== undefined ? (p * 100).toFixed(1) + '%' : '—');

  const getStageCard = (stageNum, data, title) => {
    if (!data) return null;

    const isPositive = data.escalated !== undefined ? data.escalated : data.eligibility_shortlist;

    return (
      <div className={`result-card ${isPositive ? 'result-positive' : 'result-negative'}`}>
        <div className="result-header">
          <h4>Stage {stageNum}: {title}</h4>
          <span className={`result-badge ${isPositive ? 'badge-positive' : 'badge-negative'}`}>
            {isPositive ? 'Positive' : 'Negative'}
          </span>
        </div>
        <div className="result-metrics">
          {data.probability !== undefined && (
            <div className="metric">
              <span className="metric-label">Probability</span>
              <span className="metric-value">{formatProb(data.probability)}</span>
            </div>
          )}
          {data.threshold !== undefined && (
            <div className="metric">
              <span className="metric-label">Threshold</span>
              <span className="metric-value">{formatProb(data.threshold)}</span>
            </div>
          )}
          {data.eligible_amyloid !== undefined && (
            <div className="metric">
              <span className="metric-label">Amyloid Positive</span>
              <span className="metric-value">{data.eligible_amyloid ? 'Yes' : 'No'}</span>
            </div>
          )}
          {data.aria_risk_flag !== undefined && (
            <div className="metric">
              <span className="metric-label">ARIA Risk</span>
              <span className="metric-value">{data.aria_risk_flag ? 'Yes' : 'No'}</span>
            </div>
          )}
          {data.eligibility_shortlist !== undefined && (
            <div className="metric">
              <span className="metric-label">Treatment Eligible</span>
              <span className="metric-value">{data.eligibility_shortlist ? 'Yes' : 'No'}</span>
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="prediction-results">
      <div className="results-grid">
        {getStageCard(1, stage1, 'Basic Screening')}
        {getStageCard(2, stage2, 'Blood Biomarkers')}
        {getStageCard(3, stage3, 'MRI Analysis')}
        {getStageCard(4, stage4, 'Treatment Eligibility')}
      </div>

      <div className="final-recommendation">
        <h3>📋 Final Recommendation</h3>
        <p>{final_recommendation}</p>
      </div>

      <div className="results-disclaimer">
        <p>
          ⚠️ These results are generated by machine learning models for research purposes only.
          They do not constitute a medical diagnosis. Clinical correlation and professional
          judgment are required.
        </p>
      </div>
    </div>
  );
}
