/**
 * Standard clinical demo presets for validation and evaluation.
 * Grounded in ADNI clinical feature distributions and model thresholds.
 */

export const CLINICAL_PRESETS = [
  {
    id: 'candidate',
    title: 'Shortlist Candidate',
    subtitle: 'Escalates through all 4 stages to treatment eligibility',
    badge: 'Candidate',
    badgeVariant: 'badge-emerald',
    dotColor: '#10b981',
    description: 'Patient with MCI cognitive profile, elevated plasma p-tau217, hippocampal atrophy, amyloid PET positivity, and low ARIA microhemorrhage risk.',
    data: {
      AGE: 75,
      PTEDUCAT: 16,
      MMSCORE: 27,
      APOE4: 1,
      PTGENDER: 0,
      pT217_F: 0.55,
      AB42_AB40_F: 0.055,
      NfL_Q: 25.0,
      GFAP_Q: 220.0,
      HIPPO_NORM: 0.0042,
      VENTRICLE_NORM: 0.038,
      CORTICAL_THICKNESS_AVG: 2.15,
      TOTAL_WMH: 5.2,
      AMYLOID_STATUS: 1,
      MICROHEM_COUNT: 2,
    },
  },
  {
    id: 'aria_risk',
    title: 'ARIA Safety Concern',
    subtitle: 'Amyloid+ but excluded due to high ARIA edema/hemorrhage risk',
    badge: 'Safety Alert',
    badgeVariant: 'badge-amber',
    dotColor: '#f59e0b',
    description: 'Patient meets biomarker criteria for AD, but homozygous APOE ε4/ε4 or microhemorrhage count >= 5 creates high risk for ARIA complications.',
    data: {
      AGE: 74,
      PTEDUCAT: 16,
      MMSCORE: 26,
      APOE4: 2, // Homozygous APOE4 triggers ARIA risk
      PTGENDER: 1,
      pT217_F: 0.60,
      AB42_AB40_F: 0.050,
      NfL_Q: 28.0,
      GFAP_Q: 240.0,
      HIPPO_NORM: 0.0040,
      VENTRICLE_NORM: 0.040,
      CORTICAL_THICKNESS_AVG: 2.10,
      TOTAL_WMH: 6.0,
      AMYLOID_STATUS: 1,
      MICROHEM_COUNT: 1,
    },
  },
  {
    id: 'low_risk',
    title: 'Cognitive Stable / Reassurance',
    subtitle: 'Stops early at Stage 1, avoiding invasive downstream procedures',
    badge: 'Low Risk',
    badgeVariant: 'badge-cyan',
    dotColor: '#06b6d4',
    description: 'Non-converter profile with preserved cognitive scores (MMSE 29) and no APOE ε4 alleles. Non-escalation saves patient from blood draws, MRI, and PET scans.',
    data: {
      AGE: 65,
      PTEDUCAT: 18,
      MMSCORE: 29,
      APOE4: 0,
      PTGENDER: 1,
      pT217_F: 0.10,
      AB42_AB40_F: 0.110,
      NfL_Q: 9.0,
      GFAP_Q: 85.0,
      HIPPO_NORM: 0.0072,
      VENTRICLE_NORM: 0.016,
      CORTICAL_THICKNESS_AVG: 2.80,
      TOTAL_WMH: 0.8,
      AMYLOID_STATUS: 0,
      MICROHEM_COUNT: 0,
    },
  },
  {
    id: 'biomarker_neg',
    title: 'Blood Biomarker Discordant',
    subtitle: 'Cognitive flags present, but plasma biomarkers negative (Stops at Stage 2)',
    badge: 'Stage 2 Stop',
    badgeVariant: 'badge-cyan',
    dotColor: '#38bdf8',
    description: 'Flagged on initial screening (MMSE 26), but normal plasma p-tau217 (<0.20) and Aβ42/40 stops the cascade before expensive structural neuroimaging.',
    data: {
      AGE: 73,
      PTEDUCAT: 14,
      MMSCORE: 26,
      APOE4: 0,
      PTGENDER: 0,
      pT217_F: 0.12,
      AB42_AB40_F: 0.098,
      NfL_Q: 11.5,
      GFAP_Q: 92.0,
      HIPPO_NORM: 0.0065,
      VENTRICLE_NORM: 0.022,
      CORTICAL_THICKNESS_AVG: 2.65,
      TOTAL_WMH: 1.5,
      AMYLOID_STATUS: 0,
      MICROHEM_COUNT: 0,
    },
  },
];
